### PR TITLE
Fix capability

### LINKED ISSUE #35: Set capability on the binary file failed on second run
I using this role on my rpi (rasperry pi os bullseye)

on my first run:
```bash
TASK [caddy_ansible.caddy_ansible : Set capability on the binary file to be able to bind to TCP port <1024] ***********
changed: [zigbeepi.lan]
```

on my second run:
```
TASK [caddy_ansible.caddy_ansible : Set capability on the binary file to be able to bind to TCP port <1024] ***********
fatal: [zigbeepi.lan]: FAILED! => {"changed": false, "msg": "Unable to get capabilities of /usr/local/bin/caddy", "stderr": "", "stderr_lines": [], "stdout": "/usr/local/bin/caddy cap_net_bind_service=eip", "stdout_lines": ["/usr/local/bin/caddy cap_net_bind_service=eip"]}
```

maybe this helps https://github.com/ansible/ansible/issues/72662

### PR DESCRIPTION
**Pull request by b-reich**
fix #35

### CODE REVIEW

**Comment by joelnb** [comment]
Hi @b-reich,

Appreciate your contribution and sorry for the slow response on this one. I don't see the harm in this & I think eventually we should migrate everything over to this way of referencing the tasks.

That said I would be interested to understand more about why this fixes your issue - it doesn't make much sense to me and I have been able to run against a bullseye Raspberry Pi without encountering the same issue so I don't think the target of is the cause of the problem. Are you able to reproduce the original issue with extra verbosity enabled in ansible (e.g. `-vvv`)?

**Comment by b-reich** [comment]
@joelnb no worries. 
I am not 100% sure about the referencing the "long module name" the "short module name" should redirect to the new one (https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml).

May just installing the "https://github.com/ansible-collections/community.general" fix the issue. May it depends on the installed ansible version or the libcap version too. (Or a mix between both)
I can test it again the next days.

**Comment by joelnb** [comment]
I did a bit more testing and I do consistently see the task reporting as changed when it runs for a second time, I just have never seen it fail like you have. Adding the changes from this MR & installing the collection did not change the behaviour of always reporting changed but switching the capability from `cap_net_bind_service+eip` to `cap_net_bind_service=eip` seems to solve it. I will do a bit more research into what I have seen there because I am not sure it would be correct to make that switch.

**Comment by iangregsondev** [comment]
> I did a bit more testing and I do consistently see the task reporting as changed when it runs for a second time, I just have never seen it fail like you have. Adding the changes from this MR & installing the collection did not change the behaviour of always reporting changed but switching the capability from `cap_net_bind_service+eip` to `cap_net_bind_service=eip` seems to solve it. I will do a bit more research into what I have seen there because I am not sure it would be correct to make that switch.

Hi, I just got this same problem on the latest ubuntu. Changing the +eip to =eip - worked for me.

**Comment by iangregsondev** [comment]
> > I did a bit more testing and I do consistently see the task reporting as changed when it runs for a second time, I just have never seen it fail like you have. Adding the changes from this MR & installing the collection did not change the behaviour of always reporting changed but switching the capability from `cap_net_bind_service+eip` to `cap_net_bind_service=eip` seems to solve it. I will do a bit more research into what I have seen there because I am not sure it would be correct to make that switch.
> 
> Hi, I just got this same problem on the latest ubuntu. Changing the +eip to =eip - worked for me.

Opps let me take that back :-(

Second run still fails.

I am going to ignore this error on second run and I presume that will be ok

**Comment by joelnb** [comment]
Hi @iangregsondev, when you say it fails do you mean that the task actually fails (as reported by @b-reich) or you just get the incorrect change behaviour I saw?

If the task does fail for you I would appreciate it if you are able to run your ansible command with `-vvv` and try to provide some more info on what is going wrong here.

**Comment by iangregsondev** [comment]
> Hi @iangregsondev, when you say it fails do you mean that the task actually fails (as reported by @b-reich) or you just get the incorrect change behaviour I saw?
> 
> If the task does fail for you I would appreciate it if you are able to run your ansible command with `-vvv` and try to provide some more info on what is going wrong here.

Sorry, should have been more specific. It gives "Unable to get capabilities of /usr/local/bin/caddy"

My role is an exact copy of yours just with the changes we mentioned and also i added ignore_errors..

FYI:

```
- name: Set capability on the binary file to be able to bind to TCP port <1024
  capabilities:
    path: "{{ caddy_bin }}"
    capability: cap_net_bind_service=eip
    state: present
  when: caddy_setcap
#  ignore_errors: true
```

Here is part of the log, I have sanitized it to remove my IP.

```
TASK [caddy_ansible.caddy_ansible.modified : Set capability on the binary file to be able to bind to TCP port <1024] ****************************************************************************************************************
task path: /Volumes/Data/Development/Personal/ansible/roles/caddy_ansible.caddy_ansible.modified/tasks/main.yml:122
<142.x.x.x> ESTABLISH SSH CONNECTION FOR USER: root
<142.x.x.x> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/ian/.ansible/cp/abe047f1c3 142.x.x.x '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<142.x.x.x> (0, b'/root\n', b'')
<142.x.x.x> ESTABLISH SSH CONNECTION FOR USER: root
<142.x.x.x> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/ian/.ansible/cp/abe047f1c3 142.x.x.x '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148 `" && echo ansible-tmp-1641753467.407145-99055-39867200383148="` echo /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148 `" ) && sleep 0'"'"''
<142.x.x.x> (0, b'ansible-tmp-1641753467.407145-99055-39867200383148=/root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148\n', b'')
redirecting (type: modules) ansible.builtin.capabilities to community.general.capabilities
Using module file /Users/ian/.ansible/collections/ansible_collections/community/general/plugins/modules/capabilities.py
<142.x.x.x> PUT /Users/ian/.ansible/tmp/ansible-local-98814g17eluf2/tmp96grmzgm TO /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148/AnsiballZ_capabilities.py
<142.x.x.x> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/ian/.ansible/cp/abe047f1c3 '[142.x.x.x]'
<142.x.x.x> (0, b'sftp> put /Users/ian/.ansible/tmp/ansible-local-98814g17eluf2/tmp96grmzgm /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148/AnsiballZ_capabilities.py\n', b'')
<142.x.x.x> ESTABLISH SSH CONNECTION FOR USER: root
<142.x.x.x> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/ian/.ansible/cp/abe047f1c3 142.x.x.x '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148/ /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148/AnsiballZ_capabilities.py && sleep 0'"'"''
<142.x.x.x> (0, b'', b'')
<142.x.x.x> ESTABLISH SSH CONNECTION FOR USER: root
<142.x.x.x> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/ian/.ansible/cp/abe047f1c3 -tt 142.x.x.x '/bin/sh -c '"'"'/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148/AnsiballZ_capabilities.py && sleep 0'"'"''
<142.x.x.x> (1, b'\r\n{"stdout": "/usr/local/bin/caddy cap_net_bind_service=eip", "stderr": "", "failed": true, "msg": "Unable to get capabilities of /usr/local/bin/caddy", "invocation": {"module_args": {"path": "/usr/local/bin/caddy", "capability": "cap_net_bind_service=eip", "state": "present"}}}\r\n', b'Shared connection to 142.x.x.x closed.\r\n')
<142.x.x.x> Failed to connect to the host via ssh: Shared connection to 142.x.x.x closed.
<142.x.x.x> ESTABLISH SSH CONNECTION FOR USER: root
<142.x.x.x> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/ian/.ansible/cp/abe047f1c3 142.x.x.x '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1641753467.407145-99055-39867200383148/ > /dev/null 2>&1 && sleep 0'"'"''
<142.x.x.x> (0, b'', b'')
fatal: [my-node01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "capability": "cap_net_bind_service=eip",
            "path": "/usr/local/bin/caddy",
            "state": "present"
        }
    },
    "msg": "Unable to get capabilities of /usr/local/bin/caddy",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "/usr/local/bin/caddy cap_net_bind_service=eip",
    "stdout_lines": [
        "/usr/local/bin/caddy cap_net_bind_service=eip"
    ]
}


```

**Comment by joelnb** [comment]
I think the reason that it works for you with the included change is because it's forcing your to get this change included: https://github.com/ansible-collections/community.general/pull/1110/files

I'm not sure why I don't need that (even when using an older Ansible version I can't reproduce) but I'm okay to go ahead with this if it helps resolve things when this does happen.

Thanks for the contribution!

**Pull request merged**
